services:
  grafana:
    image: ghcr.io/fuck-you-isp/grafana:main
    # build: ../grafana
    ports:
      - '80:3000'
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: grafana
    container_name: grafana
  prometheus:
    image: ghcr.io/fuck-you-isp/prometheus:main
    # build: ../prometheus
    # ports:
    #   - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=2d'
    restart: unless-stopped
    container_name: prometheus
  network-exporter:
    image: ghcr.io/fuck-you-isp/network-exporter:main
    # build: ../network-exporter
    # ports:
    #   - '9427:9427'
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    privileged: true
    container_name: network-exporter